export {default as LayoutModal} from './layoutModal'
export {default as MainModal} from './mainModal'
export {default as SuccessModal} from './successModal'
export {default as OpenHeroModal} from './openHeroModal'
export {default as CongratsModal} from './congratsModal'
